// REF https://buffer.com/library/words-and-phrases-that-convert-ultimate-list/
const powerWordsEN = [  
    'You',
    'Free',
    'Because',
    'Instantly',
    'New',

    'Suddenly',
    'Now',
    'Announcing',
    'Introducing',
    'Improvement',
    'Amazing',
    'Sensational',
    'Remarkable',
    'Revolutionary',
    'Startling',
    'Miracle',
    'Magic',
    'Offer',
    'Quick',
    'Easy',
    'Wanted',
    'Challenge',
    'Compare',
    'Bargain',
    'Hurry',

    'Join',
    'Become a member',
    'Come along',

    'Accordingly',
    'As a result',
    'Because',
    'Caused by',
    'Consequently',
    'Due to',
    'For this reason',
    'Since',
    'Therefore',
    'Thus',

    'Members only',
    'Login required',
    'Class full',
    'Membership now closed',
    'Ask for an invitation',
    'Apply to be one of our beta testers',
    'Exclusive offers',
    'Become an insider',
    'Be one of the few',
    'Get it before everybody else',
    'Be the first to hear about it',
    'Only available to subscribers',

    'Limited offer',
    'Supplies running out',
    'Get them while they last',
    'Sale ends soon',
    'Today only',
    'Only 10 available',
    'Only 3 left',
    'Only available here',
    'Double the offer in the next hour only',

    'Anonymous',
    'Authentic',
    'Backed',
    'Best-selling',
    'Cancel Anytime',
    'Certified',
    'Endorsed',
    'Guaranteed',
    'Ironclad',
    'Lifetime',
    'Moneyback',
    'No Obligation',
    'No Questions Asked',
    'No Risk',
    'No Strings Attached',
    'Official',
    'Privacy',
    'Protected',
    'Proven',
    'Recession-proof',
    'Refund',
    'Research',
    'Results',
    'Secure',
    'Tested',
    'Try before You Buy',
    'Verify',
    'Unconditional',

    'Improve',
    'Trust',
    'Immediately',
    'Discover',
    'Profit',
    'Learn',
    'Know',
    'Understand',
    'Powerful',
    'Best',
    'Win',
    'Hot Special',
    'More',
    'Bonus',
    'Exclusive',
    'Extra',
    'You',
    'Free',
    'Health',
    'Guarantee',
    'New',
    'Proven',
    'Safety',
    'Money',
    'Now',
    'Today',
    'Results',
    'Protect',
    'Help',
    'Easy',
    'Amazing',
    'Latest',
    'Extraordinary',
    'How to',
    'Worst',
    'Ultimate',
    'Hot',
    'First',
    'Big',
    'Anniversary',
    'Premiere',
    'Basic',
    'Complete',
    'Save',
    'Plus!',
    'Create',
]

const powerWordsES = []

export {powerWordsES,powerWordsEN}
