import cheerio from 'cheerio'
// import normalizeUrl from 'normalize-url';

export async function get({params}) {
	let {url} = params
	url = /^http/.test(url) ? url : `http://${url}`

	let res = await fetch(url)
	if (!res.ok) {
		url = normalizeUrl(url)
		let res = await fetch(url)
	} 

	const html = await res.text()
	const $ = cheerio.load(html)

	return {
		body: [
			{ 
				title: 'general',
				rules: [
					{
						name: 'Meta content type',
						info: `You should always specify the encoding used for an HTML or XML page. If you don't, you risk that characters in your content are incorrectly interpreted. This is not just an issue of human readability, increasingly machines need to understand your data too. A character encoding declaration is also needed to process non-ASCII characters entered by the user in forms, in URLs generated by scripts, and so forth`,
						value: $('meta[http-equiv="Content-Type"]')?.attr('content'),
						ref: 'https://www.w3.org/International/questions/qa-html-encoding-declarations',
					},{
						name: 'Viewport',
						info: "Pages optimized for a variety of devices must include a meta viewport tag in the head of the document. A meta viewport tag gives the browser instructions on how to control the page's dimensions and scaling",
						value: $('meta[name=viewport]')?.attr('content'),
						ref: 'https://developers.google.com/speed/docs/insights/ConfigureViewport'
					},{
						name: 'Content-Language',
						info: "Describe the language(s) intended for the audience",
						value: $('html[lang]')?.attr('lang'),
						ref: 'https://developers.google.com/speed/docs/insights/ConfigureViewport'
					},
				]

			},{ 

				title: 'seo',
				rules: [
					{
						name: "Title",
						info: "The title tag is the first thing a potential visitor will take notice of when performing a search and Google (and other search engines) look at your title tag, amongst other things, to help make sense of your page",
						value: $('title')?.text(),
						ref: 'https://ahrefs.com/blog/title-tag-seo/',
					},{
						name: 'Description',
						info: "Describe what a page is about. It can appear in search results as a snippet under the title tag to provide more context",
						value: $('meta[name="description"]')?.attr('content'),
						ref: 'https://ahrefs.com/blog/meta-description/',
					},{
						name: 'H1',
						info: "Commonly used to mark up a web page title",
						value: $('h1')?.text()?.trim(),
						rules: [
							{
								name: 'Use only one H1 per page',
								value:  ( $('h1')?.length == 1 ),
							}, {
								name: 'Keep H1 tags short < 70 characters',
								value: ( $('h1')?.text()?.length < 70 )
							}
						],
						ref: 'https://ahrefs.com/blog/h1-tag/',
					},
				]

			},{ 

				title: 'Open Graph Meta Tags',
				// title: 'Open Graph Meta Tags',
				// description: "Open Graph meta tags are snippets of code that control how URLs are displayed when shared on social media",
				// ref: 'https://ahrefs.com/blog/open-graph-meta-tags/',
				rules: [
					{
						name: 'og:title',
						info: 'The title of your page',
						value: $('meta[property="og:title"],meta[name="og:title"]')?.attr('content')
					},{
						name: 'og:url',
						info: "The URL of the content",
						value: $('meta[property="og:url"],meta[name="og:url"]')?.attr('content')
					},{
						name: 'og:image',
						info: "The URL of an image for the social snippet",
						value: $('meta[property^="og:image"],meta[name^="og:image"]')?.attr('content'),
					},{
						name: 'og:type',
						info: "The URL of an image for the social snippet",
						value: $('meta[property="og:type"],meta[name="og:type"]')?.attr('content'),
					},{
						name: 'og:description',
						info: "The URL of an image for the social snippet",
						value: $('meta[property="og:description"],meta[name="og:description"]')?.attr('content'),
					},{
						name: 'og:locale',
						info: "Defines the content language",
						value: $('meta[property="og:locale"],meta[name="og:locale"]')?.attr('content'),
					},
				]

			}, 
			{
				title: "Titter Cards",
				ref: 'https://developer.twitter.com/en/docs/twitter-for-websites/cards/guides/getting-started',
				rules: [
					{
						name: 'twitter:card',
						info: "The card type, which will be one of “summary”, “summary_large_image”, “app”, or “player”",
						value: $('meta[name="twitter:card"]')?.attr('content')
					},{
						name: 'twitter:site',
						info: '@username for the website used in the card footer.',
						value: $('meta[name="twitter:site"]')?.attr('content'),
						required: false,
					},{
						name: 'twitter:site',
						info: '@username for the content creator / author.',
						value: $('meta[name="twitter:site"]')?.attr('content'),
						required: false,
					}
				]
			},
			{
				title: 'icons',
				rules: [
					{
						name: 'msapplication-TileImage',
						info: 'IE 10 Metro tile icon',
						value: $('meta[name="msapplication-TileImage"]')?.attr('content')
					},{
						name: 'msapplication-TileColor',
						info: 'IE 10 Metro tile color',
						value: $('meta[name="msapplication-TileColor"]')?.attr('content')
					},{
						name: 'apple-touch-icon-precomposed',
						info: '',
						value: $('link[rel="apple-touch-icon-precomposed"]')?.attr('href')
					},{
						name: 'sizes="32x32"',
						info: 'Default required by IE. Chrome and Safari may pick ico over png',
						value: $('link[rel="icon"][sizes="32x32"]')?.attr('href')
					},{
						name: 'sizes="16x16"',
						info: 'Default required by IE. Chrome and Safari may pick ico over png',
						value: $('link[rel="icon"][sizes="16x16"]')?.attr('href')
					},{
						name: 'sizes="180x180"',
						info: 'General use iOS/Android icon, auto-downscaled by devices',
						value: $('link[rel="icon"][sizes="180x180"]')?.attr('href')
					},
				]
			}
		]
	};



			// creator: $('meta[name="twitter:creator"],meta[property="twitter:creator"]')?.attr('content'),
			// twitter_image,
		// }
}